### ISSUE TITLE
The classes of the models inherits of ActiveRecord::Base and needs to be inherited to ApplicationRecord

### ISSUE THREAD

**Issue by romenigld** [radar/twist#19]
I notice in the sample models of the ebook(like page 59) has this: 
```
class Invitation < ActiveRecord::Base
class Account < ActiveRecord::Base
```
and for the Rails 5 is:
```
class Invitation < ApplicationRecord
class Account < ApplicationRecord
```

**Comment by twist-fetcher** [comment]
Thank you for these great errata reports and your patience with them. From what it looks like, I was lazy and updated the second chapter of the book to mention that the app was using Rails 5 now, but I didn't update any of the code samples... which is why you're seeing all the things you've been seeing. The code samples are for Rails 4. 

There really shouldn't be anything TOO wrong with them, but there's just some small things that need fixing up to make the reading experience much more pleasant for all involved.

So what I'm going to do is go through the whole book myself, start to finish, and follow along with it. I'll update any code that is wrong there and then when I'm done we'll have an even better book!

Thank you once again for these great comments and for reading my book. If you find anything else in there, please let me know and I will fix it up!

**Comment by romenigld** [comment]
I stopped in the "Sending Invitation". If you help me with this error I can continue and help you.
But I remember has another thing isn't  having in the css class. Page 47, the` _form.html.erb `doesn't exists classes `accept-button` and` reject-button`. Was different like `btn btn-default`. 
So I'll wait for the next version of the ebook!? When you pretend to release? I will have the next version?
thank's for reply!

**Comment by radar** [comment]
@romenigld You're right that the form's classes are wrong. I have now updated that in my local copy of the book.

I should be finished reviewing Chapter 3 by the end of this week and then I will publish a new edition. When that happens, please keep reading and letting me know about anything that doesn't look right. 

Then over the next couple of weeks I will review the remaining chapters of the book and make sure they are up to date as well.
