### ISSUE TITLE
Book repo structure

### ISSUE THREAD

**Issue by inem** [radar/twist#27]
Maybe a stupid question, but how do you make structure in [this repo](https://github.com/radar/markdown_book_test) play nice with Leanpub?

When I use the same structure, Leanpub says it is missing manuscript directory.

**Comment by radar** [comment]
That’s the trick: I don’t use this with Leanpub at all ;) this just resembles what you’d find in a manuscript directory.

My process is to copy over this stuff from this directory into a manuscript directory (inside a book’s directory) on Dropbox... mainly because I started using leanpub before they had GitHub support.

So yeah, you’ll definitely need a manuscript directory these days!
